name: graven
version: 2.0.0-RC1
go_version: ">=1.12.0"
artifacts:
- classifier: darwin
  targets:
  - executable: bin/graven
    package: .
    flags: ["-mod", "vendor"]
  archive: tgz
  env:
    GOARCH: amd64
    GOOS: darwin
- classifier: linux
  targets:
  - executable: bin/graven
    package: .
    flags: ["-mod", "vendor"]
  archive: tar.gz
  env:
    GOARCH: amd64
    GOOS: linux
- classifier: win
  targets:
  - executable: graven.exe
    package: .
    flags: ["-mod", "vendor"]
  archive: zip
  env:
    GOARCH: amd64
    GOOS: windows
repositories:
  github:
    group: cbegin
    artifact: graven
    type: github
    roles:
    - release
resources:
- LICENSE
