name: github.com/org/myProject
version: 0.0.4
artifacts:
- classifier: darwin
  targets:
  - executable: bin/gvn
    package: .
    flags: ""
    env: {}
  - executable: bin/hello
    package: ./hello
    flags: ""
    env: {}
  archive: tgz
  resources: []
  env:
    GOARCH: amd64
    GOOS: darwin
- classifier: linux
  targets:
  - executable: bin/gvn
    package: .
    flags: ""
    env: {}
  - executable: bin/hello
    package: ./hello
    flags: ""
    env: {}
  archive: tar.gz
  resources: []
  env:
    GOARCH: amd64
    GOOS: linux
- classifier: win
  targets:
  - executable: gvn.exe
    package: .
    flags: ""
    env: {}
  - executable: hello.exe
    package: ./hello
    flags: ""
    env: {}
  archive: zip
  resources: []
  env:
    GOARCH: amd64
    GOOS: windows
repositories: []
resources: []
