name: graven
version: 0.9.17-DEV
artifacts:
- classifier: darwin
  targets:
  - executable: bin/graven
    package: .
    flags: ""
    env: {}
  archive: tgz
  resources: []
  env:
    GOARCH: amd64
    GOOS: darwin
- classifier: linux
  targets:
  - executable: bin/graven
    package: .
    flags: ""
    env: {}
  archive: tar.gz
  resources: []
  env:
    GOARCH: amd64
    GOOS: linux
- classifier: win
  targets:
  - executable: graven.exe
    package: .
    flags: ""
    env: {}
  archive: zip
  resources: []
  env:
    GOARCH: amd64
    GOOS: windows
repositories:
  docker:
    url: docker.io
    group: cbegin
    artifact: graven
    file: test_fixtures/Dockerfile
    type: docker
    roles:
    - release
  artifactory:
    url: http://localhost:8081/artifactory/releases/
    group: cbegin
    artifact: graven
    type: maven
    # Supports both releases and dependencies
    roles:
    - dependency
  nexus:
    url: http://localhost:8082/nexus/content/repositories/releases/
    group: cbegin
    artifact: graven
    type: maven
    # Supports both releases and dependencies
    roles:
    - dependency
resources:
- LICENSE
