name: graven
version: 0.9.2-DEV
artifacts:
- classifier: darwin
  targets:
  - executable: bin/graven
    package: .
    flags: ""
    env: {}
  archive: tgz
  resources: []
  env:
    GOARCH: amd64
    GOOS: darwin
- classifier: linux
  targets:
  - executable: bin/graven
    package: .
    flags: ""
    env: {}
  archive: tar.gz
  resources: []
  env:
    GOARCH: amd64
    GOOS: linux
- classifier: win
  targets:
  - executable: graven.exe
    package: .
    flags: ""
    env: {}
  archive: zip
  resources: []
  env:
    GOARCH: amd64
    GOOS: windows
repositories:
#  artifactory:
#    artifact_id: graven
#    group_id: com.github.cbegin
#    roles: release, dependency
#    type: maven
#    url: http://localhost:8081/artifactory/releases/
#  github:
#    owner: cbegin
#    repo: graven
#    roles: release, dependency
#    type: github
  nexus:
    artifact_id: graven
    group_id: com.github.cbegin
    roles:
      - release
      - dependency
    type: maven
    url: http://localhost:8082/nexus/content/repositories/releases/
resources:
- LICENSE
