name: graven
version: 0.9.9-DEV
artifacts:
- classifier: darwin
  targets:
  - executable: bin/graven
    package: .
    flags: ""
    env: {}
  archive: tgz
  resources: []
  env:
    GOARCH: amd64
    GOOS: darwin
- classifier: linux
  targets:
  - executable: bin/graven
    package: .
    flags: ""
    env: {}
  archive: tar.gz
  resources: []
  env:
    GOARCH: amd64
    GOOS: linux
- classifier: win
  targets:
  - executable: graven.exe
    package: .
    flags: ""
    env: {}
  archive: zip
  resources: []
  env:
    GOARCH: amd64
    GOOS: windows
repositories:
  artifactory:
    name: ""
    url: http://localhost:8081/artifactory/releases/
    group_id: com.github.cbegin
    artifact_id: graven
    owner: ""
    repo: ""
    type: maven
    roles:
    - release
    - dependency
  nexus:
    name: ""
    url: http://localhost:8082/nexus/content/repositories/releases/
    group_id: com.github.cbegin
    artifact_id: graven
    owner: ""
    repo: ""
    type: maven
    roles:
    - release
    - dependency
resources:
- LICENSE
