name: graven
version: 0.11.2
artifacts:
- classifier: darwin
  targets:
  - executable: bin/graven
    package: .
    flags: ""
    env: {}
  archive: tgz
  resources: []
  env:
    GOARCH: amd64
    GOOS: darwin
- classifier: linux
  targets:
  - executable: bin/graven
    package: .
    flags: ""
    env: {}
  archive: tar.gz
  resources: []
  env:
    GOARCH: amd64
    GOOS: linux
- classifier: win
  targets:
  - executable: graven.exe
    package: .
    flags: ""
    env: {}
  archive: zip
  resources: []
  env:
    GOARCH: amd64
    GOOS: windows
repositories:
  github:
    url: ""
    group: cbegin
    artifact: graven
    file: ""
    type: github
    roles:
    - release
resources:
- LICENSE
