name: github.com/org/myProject
version: 0.0.1
artifacts:
- classifier: darwin
  resources: []
  env:
    GOARCH: amd64
    GOOS: darwin
  targets:
  - executable: bin/gvn
    package: .
    flags: ""
  - executable: bin/hello 
    package: ./hello
    flags: ""
  archive: tgz
- classifier: linux
  resources: []
  env:
    GOARCH: amd64
    GOOS: linux
  targets:
  - executable: bin/gvn
    package: .
    flags: ""
  - executable: bin/hello
    package: ./hello
    flags: ""
  archive: tar.gz
- classifier: win
  resources: []
  env:
    GOARCH: amd64
    GOOS: windows
  targets:
  - executable: gvn.exe
    package: .
    flags: ""
  - executable: hello.exe
    package: ./hello
    flags: ""
  archive: zip
repositories: []
