name: graven
version: 3.0.0
go_version: ">=1.12.0"
artifacts:
- classifier: darwin
  targets:
  - executable: bin/graven
    package: ./cmd
    flags: ["-ldflags", "-s"]
  archive: tgz
  env:
    GOARCH: amd64
    GOOS: darwin
- classifier: linux
  targets:
  - executable: bin/graven
    package: ./cmd
    flags: ["-ldflags", "-s"]
  archive: tar.gz
  env:
    GOARCH: amd64
    GOOS: linux
- classifier: win
  targets:
  - executable: bin/graven.exe
    package: ./cmd
    flags: ["-ldflags", "-s"]
  archive: zip
  env:
    GOARCH: amd64
    GOOS: windows
repositories:
  github:
    group: cbegin
    artifact: graven
    type: github
resources:
- LICENSE
