name: graven
version: 0.8.0
artifacts:
- classifier: darwin
  targets:
  - executable: bin/graven
    package: .
    flags: ""
    env: {}
  archive: tgz
  resources: []
  env:
    GOARCH: amd64
    GOOS: darwin
- classifier: linux
  targets:
  - executable: bin/graven
    package: .
    flags: ""
    env: {}
  archive: tar.gz
  resources: []
  env:
    GOARCH: amd64
    GOOS: linux
- classifier: win
  targets:
  - executable: graven.exe
    package: .
    flags: ""
    env: {}
  archive: zip
  resources: []
  env:
    GOARCH: amd64
    GOOS: windows
resources:
- LICENSE
repositories:
  github:
    type: github
    roles: release, dependency
    owner: cbegin
    repo: graven
  artifactory:
    type: maven
    roles: release, dependency
    url: http://localhost:8081/artifactory/releases/
  nexus:
    type: maven
    roles: release, dependency
    url: http://localhost:8082/nexus/content/repositories/releases/
